### PR TITLE
Update default parameters to SD1.4 recommendations

### PR DESCRIPTION
**Pull request by lewdogk**

### CODE REVIEW

**Comment by ljleb** [comment]
You think the bounds are good (0 to 2) or we should change them as well?

**Comment by lewdogk** [comment]
It's probably best to give them a wide range to experiment with since this is very new stuff.

**Comment by ljleb** [comment]
Okay I'll merge and update the bounds to go from -1 to 3. we can always change the titles of the sliders later to be able to change the bounds.

**Comment by Miczu** [comment]
Now I'm interested to see what happens with negative values...

**Comment by Nyxeka** [comment]
make sure to check for --no-half before doing .to(32) and .to(16)

**Comment by ljleb** [comment]
The fft needs to work in fp32. I just pushed a fix that reverts to the original precision after the fft

**Comment by Miczu** [comment]
image
Looks like once I loaded original version, the old values persists. Probably can fix it by deleting it from config...
Update/reinstall didn't do it.

**Comment by Miczu** [comment]
`    "customscript/main.py/txt2img/Enable/visible": true,
    "customscript/main.py/txt2img/Enable/value": false,`
Probably needs better name for checkbox.

**Comment by Miczu** [comment]
Deleting those line from ui-config fixed it.

**Comment by ljleb** [comment]
Yeah you can delete the lines. We can also rename the sliders later if we end up shrinking the sliders range.

**Pull request merged**
